# roles/wordpress/tasks/main.yml
---
- hosts: localhost
  tasks:
    - include_vars: ../vars/CentOS.yml
      tags: wordpress

    - include_tasks: install.yml
      tags: wordpress

    - stat:
        path: "{{ wordpress_directory }}/wp-salts.php"
      register: salt_file

    - include_tasks: salt.yml
      when: not salt_file.stat.exists

    - include_tasks: config.yml

    - include_tasks: plugins.yml

    - include_tasks: themes.yml
